services:
  obs-connection-editor:
    build: .
    container_name: obs-connection-editor
    ports:
      - "3112:3112"
    environment:
      - NODE_ENV=production
      - SMB_ADDRESS=${SMB_ADDRESS:-192.168.40.145}
      - SMB_SHARE_NAME=${SMB_SHARE_NAME:-OBS Multi}
      - SMB_USERNAME=${SMB_USERNAME:-guest}
      - SMB_PASSWORD=${SMB_PASSWORD:-}
      - SMB_FILE_PATH=${SMB_FILE_PATH:-src/App.svelte}
    restart: unless-stopped
    volumes:
      # Optional: Mount a config directory for certificates
      - ./data:/app/data
    networks:
      - obs-network

networks:
  obs-network:
    driver: bridge

# Optional: For development with external SMB server
# volumes:
#   smb-data:
#     external: true